export { default as pic8 } from './pic8.png';
export { default as pic15 } from './pic15.png';
export { default as pic16 } from './pic16.png';
export { default as pic1 } from './pic1.jpg';
export { default as pic5 } from './pic5.jpg';
export { default as pic3 } from './pic3.jpg';
export { default as pic4 } from './pic4.jpg';
export { default as pic12 } from './pic12.jpg';
export { default as pic6 } from './pic6.jpg';
export { default as pic77 } from './pic77.png';
export { default as pic9} from './pic9.jpg';
export { default as pic10} from './pic10.jpg';
export { default as pic11} from './pic11.jpg';
export { default as pic13} from './pic13.jpg';