export { default as turki1 } from './turki1.jpg';
export { default as turki2 } from './turki2.jpg';
export { default as turki3 } from './turki3.jpg';
export { default as turki4 } from './turki4.jpg';
export { default as turki5 } from './turki5.jpg';
export { default as turki6 } from './turki6.jpg';
export { default as turki7 } from './turki7.jpg';
export { default as turki8 } from './turki8.jpg';
export { default as turki9 } from './turki9.jpg';