import * as sikan from "../assets/images/sikan";
import * as bodiyat from "../assets/images/bodiyat";
import * as n3ail from "../assets/images/n3ail";
import * as dyar from "../assets/images/dyar";
import * as ramby from "../assets/images/ramby";
import * as malhaf from "../assets/images/malhaf";

const malhafti = {
  "malhafti": [
    { "id": 1, "type": "ڭاز صيني", "size": "عرض", "price":  200, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 2, "type": "ڭاز صيني", "size": "عرض", "price":  200, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 3, "type": "ڭاز صيني", "size": "عرض", "price":  200, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 4, "type": "ڭاز صيني", "size": "عرض", "price":  200, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 5, "type": "ڭاز صيني", "size": "عرض", "price":  200, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 6, "type": "ڭاز صيني", "size": "عرض", "price":  220, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 7, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 8, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 9, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 10, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 11, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 12, "type": "ڭاز تركي", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 13, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 14, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 15, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 16, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 17, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 18, "type": "ڭاز ميمة", "size": "عرضين", "price":  240, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 19, "type": "ڭاز طينطان", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 20, "type": "ڭاز طينطان", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 21, "type": "ڭاز طينطان", "size": "عرض", "price":  550, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 22, "type": "ڭاز طينطان", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 23, "type": "ڭاز طينطان", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 24, "type": "ڭاز طينطان", "size": "عرض", "price":  550, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 25, "type": "ڭاز لكوارب", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 26, "type": "ڭاز لكوارب", "size": "عرض", "price":  550, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 27, "type": "ڭاز لكوارب", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 28, "type": "ڭاز لكوارب", "size": "عرض", "price":  550, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 29, "type": "ڭاز لكوارب", "size": "عرض", "price":  500, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 30, "type": "ڭاز لكوارب", "size": "عرضين", "price":  250, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 31, "type": "ڭاز التصرار", "size": "عرض", "price":  260, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 32, "type": "ڭاز التصرار", "size": "عرضين", "price": 280, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 33, "type": "ڭاز التصرار", "size": "عرض", "price":  260, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 34, "type": "ڭاز التصرار", "size": "عرض", "price":  260, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 35, "type": "ڭاز التصرار", "size": "عرض", "price":  260, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 36, "type": "ڭاز التصرار", "size": "عرض", "price":  260, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 37, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 38, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 39, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 40, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 41, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 42, "type": "خياطة الطينطان", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 43, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },  
    { "id": 44 ,"type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },  
    { "id": 45, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 46, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "خياطة", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 47, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 48, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 49, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 50, "type": "كج الخياطة", "size": "عرض", "price":  1600, "group": "ڭاز", "category" :  "الملحف" , "image": malhaf.malhaf },
    { "id": 132, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 133, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 134, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 135, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 136, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 137, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 138, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 139, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 140, "type": "", "size": "عرض", "price": 2500, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 74, "type": "", "size": "عرضين", "price":  3000, "category": "الملحف" , "image": malhaf.malhaf },
    { "id": 51, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby1 },
    { "id": 52, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby2 },
    { "id": 53, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby3 },
    { "id": 54, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby4 },
    { "id": 55, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby5 },
    { "id": 56, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby6 },
    { "id": 57, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby7 },
    { "id": 58, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby8 },
    { "id": 59, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby9 },
    { "id": 60, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby10 },
    { "id": 61, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby11 },
    { "id": 62, "type": "رمبي بجناد", "size": "standard", "price":  180, "category": "الرمبي", "image": ramby.ramby12 },
    { "id": 63, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic1 },
    { "id": 64, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic2 },
    { "id": 65, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic3 },
    { "id": 66, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic4 },
    { "id": 67, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic5 },
    { "id": 68, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic6 },
    { "id": 69, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic7 },
    { "id": 70, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic8 },
    { "id": 71, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic9 },
    { "id": 72, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic10 },
    { "id": 73, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic11 },
    { "id": 75, "type": "بودي سامبل", "size": "standard", "price":  100, "category": "بودي", "image": bodiyat.pic13 },
    { "id": 79, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak1},
    { "id": 80, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak2 },
    { "id": 81, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak3 },
    { "id": 82, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak4 },
    { "id": 83, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak5 },
    { "id": 84, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak6 },
    { "id": 85, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak7 },
    { "id": 86, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak8 },
    { "id": 87, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak9 },
    { "id": 88, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak10 },
    { "id": 89, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak11 },
    { "id": 90, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak12 },
    { "id": 91, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak13 },
    { "id": 92, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak14 },
    { "id": 93, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak15 },
    { "id": 94, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak16 },
    { "id": 95, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak17 },
    { "id": 96, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak18 },
    { "id": 97, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak19 },
    { "id": 98, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak20 },
    { "id": 98, "type": "صاك", "size": "standard", "price":  400, "category": "صيكان", "image": sikan.sak21 },
    { "id": 99, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala1 },
    { "id": 100, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala2 },
    { "id": 101, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala3 },
    { "id": 102, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala4 },
    { "id": 103, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala5 },
    { "id": 104, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala6 },
    { "id": 105, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala7 },
    { "id": 106, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala8 },
    { "id": 107, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala9 },
    { "id": 108, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala10 },
    { "id": 109, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala11 },
    { "id": 110, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala12 },
    { "id": 111, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala13 },
    { "id": 112, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala14 },
    { "id": 113, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala15 },
    { "id": 114, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala16 },
    { "id": 115, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala17 },
    { "id": 116, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala18 },
    { "id": 117, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala19 },
    { "id": 118, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala20 },
    { "id": 119, "type": "", "size": "35-40", "price":  200, "category": "نعايل", "image": n3ail.n3ala21 },
    { "id": 120, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar1 },
    { "id": 121, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar2 },
    { "id": 122, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar3 },
    { "id": 123, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar4 },
    { "id": 124, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar5 },
    { "id": 125, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar6 },
    { "id": 126, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar7 },
    { "id": 127, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar8 },
    { "id": 128, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar9 },
    { "id": 129, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar10 },
    { "id": 130, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar11 },
    { "id": 131, "type": "", "size": "standard", "price": 2500, "category": "ديار", "image": dyar.dyar12 }
  ]
}
export {malhafti}